USE [IDENTClinic3]
GO

/****** Object:  Table [dbo].[Doctors]    Script Date: 30.07.2024 12:24:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Doctors](
	[ID] [int] NOT NULL,
	[ITN] [char](12) NOT NULL,
	[ID_Persons] [int] NOT NULL,
 CONSTRAINT [PK_Doctors] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_Doctors_Persons] UNIQUE NONCLUSTERED 
(
	[ID_Persons] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Doctors]  WITH CHECK ADD  CONSTRAINT [FK_Doctors_Persons] FOREIGN KEY([ID_Persons])
REFERENCES [dbo].[Persons] ([ID])
GO

ALTER TABLE [dbo].[Doctors] CHECK CONSTRAINT [FK_Doctors_Persons]
GO

